version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # Adicione esta seção para carregar o .env
    env_file:
      - .env
    networks:
      - app-network
    # Se você tiver uma configuração de banco de dados, ela deve ser adicionada aqui
    # depends_on:
    #   - db

networks:
  app-network:
    driver: bridge