# docker-compose.yml (Corrigido)

services:
  backend:
    build: ./backend
    container_name: blausight-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - blausight_data:/app/instance
    environment:
      - SECRET_KEY=uma-chave-secreta-super-segura-para-desenvolvimento

  frontend:
    build: ./frontend
    container_name: blausight-frontend
    restart: always
    ports:
      # Mapeamos a porta 80 do container (Nginx) para a porta 5173 da sua máquina
      - "5173:80"
    depends_on:
      - backend

volumes:
  blausight_data: