services:
  db:
    image: mysql:8.0
    container_name: blausight-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    # COMANDO CORRIGIDO: Removido 'gevent' para estabilidade e ajustado o bind.
    command: gunicorn --workers 2 --timeout 300 --bind 0.0.0.0:5000 'app:create_app()'
    container_name: blausight-backend
    restart: always
    ports:
      # PORTA CORRIGIDA: Mapeia a porta 8000 do seu computador para a 5000 do container.
      - "8000:5000"
    volumes:
      # VOLUME ADICIONADO: Sincroniza o código local com o container para desenvolvimento.
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: blausight-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Impede que o node_modules local sobrescreva o do container
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: