services:
  backend:
    build: ./backend
    container_name: blausight-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - blausight_db:/app/database
      - blausight_model:/app/model
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 "app:create_app()"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000/api
    container_name: blausight-frontend
    ports:
      - "5173:80" 
    depends_on:
      - backend

volumes:
  blausight_db:
  blausight_model: