"""Criação inicial das tabelas

Revision ID: 0ec659b507c0
Revises: 
Create Date: 2025-06-26 16:54:01.917041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec659b507c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('gestor', sa.String(length=255), nullable=True),
    sa.Column('data_desvio', sa.String(length=50), nullable=True),
    sa.Column('produto', sa.String(length=255), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('id_desvio', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('causa_raiz', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_desvio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deviations')
    # ### end Alembic commands ###
