"""Add AI analysis fields to Deviation

Revision ID: 415c4bb4d31d
Revises: be49cfdef6c6
Create Date: 2025-07-08 14:03:20.500280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '415c4bb4d31d'
down_revision = 'be49cfdef6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deviations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failure_analysis', sa.Text(), nullable=True))
        batch_op.alter_column('keywords',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deviations', schema=None) as batch_op:
        batch_op.alter_column('keywords',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('failure_analysis')

    # ### end Alembic commands ###
