"""Add file_path to Deviation model

Revision ID: be49cfdef6c6
Revises: fabb1b219bfb
Create Date: 2025-07-08 13:42:59.928516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be49cfdef6c6'
down_revision = 'fabb1b219bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deviations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deviations', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
