"""Criação inicial das tabelas

Revision ID: fabb1b219bfb
Revises: 
Create Date: 2025-07-08 12:57:19.927695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabb1b219bfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_desvio', sa.String(length=100), nullable=True),
    sa.Column('data_identificacao', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('causa_raiz', sa.Text(), nullable=True),
    sa.Column('acao_corretiva', sa.Text(), nullable=True),
    sa.Column('status_acao', sa.String(length=50), nullable=True),
    sa.Column('classificacao_desvio', sa.String(length=50), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_desvio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deviations')
    # ### end Alembic commands ###
